// New DOR Data (2017-2022) - Total dropout rates + Synthetic Gender Data
export const newDorData = [
  {
    "state": "Andaman & Nicobar Islands",
    "year": "2017-18",
    "Primary": 0.2,
    "UpperPrimary": 0.0,
    "Secondary": 7.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0.4,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 8.61,
    "Secondary_Girls": 6.79
  },
  {
    "state": "Andhra Pradesh",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.2,
    "Secondary": 22.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.24,
    "UpperPrimary_Girls": 0.16,
    "Secondary_Boys": 23.12,
    "Secondary_Girls": 22.68
  },
  {
    "state": "Arunachal Pradesh",
    "year": "2017-18",
    "Primary": 8.1,
    "UpperPrimary": 7.2,
    "Secondary": 19.0,
    "Primary_Boys": 6.52,
    "Primary_Girls": 9.68,
    "UpperPrimary_Boys": 5.83,
    "UpperPrimary_Girls": 8.57,
    "Secondary_Boys": 16.88,
    "Secondary_Girls": 21.12
  },
  {
    "state": "Assam",
    "year": "2017-18",
    "Primary": 10.1,
    "UpperPrimary": 5.4,
    "Secondary": 33.7,
    "Primary_Boys": 10.8,
    "Primary_Girls": 9.4,
    "UpperPrimary_Boys": 4.92,
    "UpperPrimary_Girls": 5.88,
    "Secondary_Boys": 34.6,
    "Secondary_Girls": 32.8
  },
  {
    "state": "Bihar",
    "year": "2017-18",
    "Primary": 5.1,
    "UpperPrimary": 13.3,
    "Secondary": 32.1,
    "Primary_Boys": 5.33,
    "Primary_Girls": 4.87,
    "UpperPrimary_Boys": 12.53,
    "UpperPrimary_Girls": 14.07,
    "Secondary_Boys": 33.01,
    "Secondary_Girls": 31.19
  },
  {
    "state": "Chandigarh",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 0.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 0,
    "Secondary_Girls": 0
  },
  {
    "state": "Chhattisgarh",
    "year": "2017-18",
    "Primary": 1.9,
    "UpperPrimary": 5.0,
    "Secondary": 20.1,
    "Primary_Boys": 2.2,
    "Primary_Girls": 1.6,
    "UpperPrimary_Boys": 3.73,
    "UpperPrimary_Girls": 6.27,
    "Secondary_Boys": 19.19,
    "Secondary_Girls": 21.01
  },
  {
    "state": "Dadra & Nagar Haveli",
    "year": "2017-18",
    "Primary": 0.1,
    "UpperPrimary": 2.3,
    "Secondary": 25.1,
    "Primary_Boys": 0.2,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.24,
    "UpperPrimary_Girls": 3.36,
    "Secondary_Boys": 23.27,
    "Secondary_Girls": 26.93
  },
  {
    "state": "Daman & Diu",
    "year": "2017-18",
    "Primary": 0.4,
    "UpperPrimary": 1.7,
    "Secondary": 21.2,
    "Primary_Boys": 0.8,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 3.4,
    "Secondary_Boys": 19.76,
    "Secondary_Girls": 22.64
  },
  {
    "state": "Delhi",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 1.6,
    "Secondary": 17.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.41,
    "UpperPrimary_Girls": 1.79,
    "Secondary_Boys": 17.96,
    "Secondary_Girls": 17.04
  },
  {
    "state": "Goa",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 7.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 4.95,
    "Secondary_Girls": 9.65
  },
  {
    "state": "Gujarat",
    "year": "2017-18",
    "Primary": 1.7,
    "UpperPrimary": 7.5,
    "Secondary": 20.6,
    "Primary_Boys": 1.52,
    "Primary_Girls": 1.88,
    "UpperPrimary_Boys": 8.18,
    "UpperPrimary_Girls": 6.82,
    "Secondary_Boys": 21.26,
    "Secondary_Girls": 19.94
  },
  {
    "state": "Haryana",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.4,
    "Secondary": 13.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 12.39,
    "Secondary_Girls": 14.61
  },
  {
    "state": "Himachal Pradesh",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.6,
    "Secondary": 6.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.2,
    "Secondary_Boys": 4.95,
    "Secondary_Girls": 8.05
  },
  {
    "state": "Jammu & Kashmir",
    "year": "2017-18",
    "Primary": 2.9,
    "UpperPrimary": 1.2,
    "Secondary": 3.4,
    "Primary_Boys": 2.02,
    "Primary_Girls": 3.78,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 2.4,
    "Secondary_Boys": 3.08,
    "Secondary_Girls": 3.72
  },
  {
    "state": "Jharkhand",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 9.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 8.57,
    "Secondary_Girls": 10.43
  },
  {
    "state": "Karnataka",
    "year": "2017-18",
    "Primary": 1.7,
    "UpperPrimary": 2.6,
    "Secondary": 24.3,
    "Primary_Boys": 0,
    "Primary_Girls": 3.4,
    "UpperPrimary_Boys": 1.44,
    "UpperPrimary_Girls": 3.76,
    "Secondary_Boys": 22.28,
    "Secondary_Girls": 26.32
  },
  {
    "state": "Kerala",
    "year": "2017-18",
    "Primary": 0.1,
    "UpperPrimary": 0.0,
    "Secondary": 12.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0.2,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 10.53,
    "Secondary_Girls": 13.47
  },
  {
    "state": "Lakshadweep",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 1.8,
    "Secondary": 5.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 2.64,
    "UpperPrimary_Girls": 0.96,
    "Secondary_Boys": 5.7,
    "Secondary_Girls": 5.3
  },
  {
    "state": "Madhya Pradesh",
    "year": "2017-18",
    "Primary": 4.0,
    "UpperPrimary": 6.4,
    "Secondary": 24.2,
    "Primary_Boys": 3.99,
    "Primary_Girls": 4.01,
    "UpperPrimary_Boys": 7.12,
    "UpperPrimary_Girls": 5.68,
    "Secondary_Boys": 24.39,
    "Secondary_Girls": 24.01
  },
  {
    "state": "Maharashtra",
    "year": "2017-18",
    "Primary": 0.2,
    "UpperPrimary": 1.7,
    "Secondary": 12.6,
    "Primary_Boys": 0.4,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.73,
    "UpperPrimary_Girls": 1.67,
    "Secondary_Boys": 11.38,
    "Secondary_Girls": 13.82
  },
  {
    "state": "Manipur",
    "year": "2017-18",
    "Primary": 3.4,
    "UpperPrimary": 0.5,
    "Secondary": 6.0,
    "Primary_Boys": 3.12,
    "Primary_Girls": 3.68,
    "UpperPrimary_Boys": 0.2,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 6.27,
    "Secondary_Girls": 5.73
  },
  {
    "state": "Meghalaya",
    "year": "2017-18",
    "Primary": 1.7,
    "UpperPrimary": 5.9,
    "Secondary": 17.5,
    "Primary_Boys": 1.77,
    "Primary_Girls": 1.63,
    "UpperPrimary_Boys": 3.62,
    "UpperPrimary_Girls": 8.18,
    "Secondary_Boys": 16.23,
    "Secondary_Girls": 18.77
  },
  {
    "state": "Mizoram",
    "year": "2017-18",
    "Primary": 8.0,
    "UpperPrimary": 7.0,
    "Secondary": 19.7,
    "Primary_Boys": 6.87,
    "Primary_Girls": 9.13,
    "UpperPrimary_Boys": 7.4,
    "UpperPrimary_Girls": 6.6,
    "Secondary_Boys": 18.15,
    "Secondary_Girls": 21.25
  },
  {
    "state": "Nagaland",
    "year": "2017-18",
    "Primary": 4.6,
    "UpperPrimary": 3.9,
    "Secondary": 13.2,
    "Primary_Boys": 5.03,
    "Primary_Girls": 4.17,
    "UpperPrimary_Boys": 3.57,
    "UpperPrimary_Girls": 4.23,
    "Secondary_Boys": 10.74,
    "Secondary_Girls": 15.66
  },
  {
    "state": "Odisha",
    "year": "2017-18",
    "Primary": 5.8,
    "UpperPrimary": 5.4,
    "Secondary": 28.3,
    "Primary_Boys": 4.56,
    "Primary_Girls": 7.04,
    "UpperPrimary_Boys": 4.45,
    "UpperPrimary_Girls": 6.35,
    "Secondary_Boys": 26.9,
    "Secondary_Girls": 29.7
  },
  {
    "state": "Puducherry",
    "year": "2017-18",
    "Primary": 3.2,
    "UpperPrimary": 1.9,
    "Secondary": 17.5,
    "Primary_Boys": 1.25,
    "Primary_Girls": 5.15,
    "UpperPrimary_Boys": 0.18,
    "UpperPrimary_Girls": 3.62,
    "Secondary_Boys": 17.7,
    "Secondary_Girls": 17.3
  },
  {
    "state": "Punjab",
    "year": "2017-18",
    "Primary": 2.9,
    "UpperPrimary": 4.0,
    "Secondary": 12.4,
    "Primary_Boys": 3.79,
    "Primary_Girls": 2.01,
    "UpperPrimary_Boys": 3.9,
    "UpperPrimary_Girls": 4.1,
    "Secondary_Boys": 12.46,
    "Secondary_Girls": 12.34
  },
  {
    "state": "Rajasthan",
    "year": "2017-18",
    "Primary": 3.4,
    "UpperPrimary": 2.8,
    "Secondary": 10.5,
    "Primary_Boys": 3.66,
    "Primary_Girls": 3.14,
    "UpperPrimary_Boys": 0.5,
    "UpperPrimary_Girls": 5.1,
    "Secondary_Boys": 8.43,
    "Secondary_Girls": 12.57
  },
  {
    "state": "Sikkim",
    "year": "2017-18",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 16.1,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 16.0,
    "Secondary_Girls": 16.2
  },
  {
    "state": "Tamil Nadu",
    "year": "2017-18",
    "Primary": 5.9,
    "UpperPrimary": 9.1,
    "Secondary": 16.2,
    "Primary_Boys": 4.61,
    "Primary_Girls": 7.19,
    "UpperPrimary_Boys": 8.72,
    "UpperPrimary_Girls": 9.48,
    "Secondary_Boys": 14.0,
    "Secondary_Girls": 18.4
  },
  {
    "state": "Telangana",
    "year": "2017-18",
    "Primary": 3.5,
    "UpperPrimary": 2.6,
    "Secondary": 17.1,
    "Primary_Boys": 2.89,
    "Primary_Girls": 4.11,
    "UpperPrimary_Boys": 2.67,
    "UpperPrimary_Girls": 2.53,
    "Secondary_Boys": 17.24,
    "Secondary_Girls": 16.96
  },
  {
    "state": "Tripura",
    "year": "2017-18",
    "Primary": 0.9,
    "UpperPrimary": 2.6,
    "Secondary": 27.2,
    "Primary_Boys": 0,
    "Primary_Girls": 1.8,
    "UpperPrimary_Boys": 2.68,
    "UpperPrimary_Girls": 2.52,
    "Secondary_Boys": 26.15,
    "Secondary_Girls": 28.25
  },
  {
    "state": "Uttarakhand",
    "year": "2017-18",
    "Primary": 3.4,
    "UpperPrimary": 2.4,
    "Secondary": 11.4,
    "Primary_Boys": 1.26,
    "Primary_Girls": 5.54,
    "UpperPrimary_Boys": 2.0,
    "UpperPrimary_Girls": 2.8,
    "Secondary_Boys": 11.63,
    "Secondary_Girls": 11.17
  },
  {
    "state": "Uttar Pradesh",
    "year": "2017-18",
    "Primary": 7.2,
    "UpperPrimary": 7.4,
    "Secondary": 19.0,
    "Primary_Boys": 4.71,
    "Primary_Girls": 9.69,
    "UpperPrimary_Boys": 6.62,
    "UpperPrimary_Girls": 8.18,
    "Secondary_Boys": 19.68,
    "Secondary_Girls": 18.32
  },
  {
    "state": "West Bengal",
    "year": "2017-18",
    "Primary": 0.2,
    "UpperPrimary": 0.0,
    "Secondary": 14.7,
    "Primary_Boys": 0.4,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 15.32,
    "Secondary_Girls": 14.08
  },
  {
    "state": "All India",
    "year": "2017-18",
    "Primary": 3.5,
    "UpperPrimary": 5.0,
    "Secondary": 18.9,
    "Primary_Boys": 2.3,
    "Primary_Girls": 4.7,
    "UpperPrimary_Boys": 3.23,
    "UpperPrimary_Girls": 6.77,
    "Secondary_Boys": 18.42,
    "Secondary_Girls": 19.38
  },
  {
    "state": "Andaman & Nicobar Islands",
    "year": "2018-19",
    "Primary": 1.0,
    "UpperPrimary": 0.0,
    "Secondary": 22.2,
    "Primary_Boys": 1.78,
    "Primary_Girls": 0.22,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 21.86,
    "Secondary_Girls": 22.54
  },
  {
    "state": "Andhra Pradesh",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 16.4,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 2.2,
    "Secondary_Boys": 15.55,
    "Secondary_Girls": 17.25
  },
  {
    "state": "Arunachal Pradesh",
    "year": "2018-19",
    "Primary": 13.8,
    "UpperPrimary": 6.7,
    "Secondary": 36.0,
    "Primary_Boys": 11.4,
    "Primary_Girls": 16.2,
    "UpperPrimary_Boys": 4.69,
    "UpperPrimary_Girls": 8.71,
    "Secondary_Boys": 36.96,
    "Secondary_Girls": 35.04
  },
  {
    "state": "Assam",
    "year": "2018-19",
    "Primary": 3.1,
    "UpperPrimary": 1.9,
    "Secondary": 31.5,
    "Primary_Boys": 1.58,
    "Primary_Girls": 4.62,
    "UpperPrimary_Boys": 0.51,
    "UpperPrimary_Girls": 3.29,
    "Secondary_Boys": 30.62,
    "Secondary_Girls": 32.38
  },
  {
    "state": "Bihar",
    "year": "2018-19",
    "Primary": 7.8,
    "UpperPrimary": 12.4,
    "Secondary": 28.5,
    "Primary_Boys": 7.87,
    "Primary_Girls": 7.73,
    "UpperPrimary_Boys": 11.16,
    "UpperPrimary_Girls": 13.64,
    "Secondary_Boys": 29.11,
    "Secondary_Girls": 27.89
  },
  {
    "state": "Chandigarh",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 0.4,
    "Secondary": 4.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 3.91,
    "Secondary_Girls": 5.09
  },
  {
    "state": "Chhattisgarh",
    "year": "2018-19",
    "Primary": 3.4,
    "UpperPrimary": 7.0,
    "Secondary": 19.8,
    "Primary_Boys": 1.06,
    "Primary_Girls": 5.74,
    "UpperPrimary_Boys": 4.93,
    "UpperPrimary_Girls": 9.07,
    "Secondary_Boys": 19.88,
    "Secondary_Girls": 19.72
  },
  {
    "state": "Dadra & Nagar Haveli",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 2.3,
    "Secondary": 20.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.55,
    "UpperPrimary_Girls": 3.05,
    "Secondary_Boys": 20.87,
    "Secondary_Girls": 20.13
  },
  {
    "state": "Daman & Diu",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 0.1,
    "Secondary": 21.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.2,
    "Secondary_Boys": 19.65,
    "Secondary_Girls": 23.75
  },
  {
    "state": "Delhi",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 14.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.06,
    "UpperPrimary_Girls": 1.14,
    "Secondary_Boys": 13.66,
    "Secondary_Girls": 16.14
  },
  {
    "state": "Goa",
    "year": "2018-19",
    "Primary": 1.5,
    "UpperPrimary": 0.9,
    "Secondary": 9.4,
    "Primary_Boys": 0.37,
    "Primary_Girls": 2.63,
    "UpperPrimary_Boys": 1.37,
    "UpperPrimary_Girls": 0.43,
    "Secondary_Boys": 7.73,
    "Secondary_Girls": 11.07
  },
  {
    "state": "Gujarat",
    "year": "2018-19",
    "Primary": 2.3,
    "UpperPrimary": 7.4,
    "Secondary": 23.8,
    "Primary_Boys": 1.41,
    "Primary_Girls": 3.19,
    "UpperPrimary_Boys": 5.67,
    "UpperPrimary_Girls": 9.13,
    "Secondary_Boys": 22.94,
    "Secondary_Girls": 24.66
  },
  {
    "state": "Haryana",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 1.9,
    "Secondary": 14.8,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 2.9,
    "UpperPrimary_Girls": 0.9,
    "Secondary_Boys": 14.67,
    "Secondary_Girls": 14.93
  },
  {
    "state": "Himachal Pradesh",
    "year": "2018-19",
    "Primary": 0.3,
    "UpperPrimary": 0.3,
    "Secondary": 7.8,
    "Primary_Boys": 0.6,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.6,
    "Secondary_Boys": 5.72,
    "Secondary_Girls": 9.88
  },
  {
    "state": "Jammu & Kashmir",
    "year": "2018-19",
    "Primary": 6.7,
    "UpperPrimary": 6.3,
    "Secondary": 17.8,
    "Primary_Boys": 4.79,
    "Primary_Girls": 8.61,
    "UpperPrimary_Boys": 6.22,
    "UpperPrimary_Girls": 6.38,
    "Secondary_Boys": 18.6,
    "Secondary_Girls": 17.0
  },
  {
    "state": "Jharkhand",
    "year": "2018-19",
    "Primary": 5.4,
    "UpperPrimary": 10.2,
    "Secondary": 22.3,
    "Primary_Boys": 3.33,
    "Primary_Girls": 7.47,
    "UpperPrimary_Boys": 7.89,
    "UpperPrimary_Girls": 12.51,
    "Secondary_Boys": 23.0,
    "Secondary_Girls": 21.6
  },
  {
    "state": "Karnataka",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 0.2,
    "Secondary": 23.4,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.4,
    "Secondary_Boys": 24.16,
    "Secondary_Girls": 22.64
  },
  {
    "state": "Kerala",
    "year": "2018-19",
    "Primary": 0.2,
    "UpperPrimary": 0.0,
    "Secondary": 9.1,
    "Primary_Boys": 0,
    "Primary_Girls": 0.4,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 7.42,
    "Secondary_Girls": 10.78
  },
  {
    "state": "Lakshadweep",
    "year": "2018-19",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 4.6,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 5.15,
    "Secondary_Girls": 4.05
  },
  {
    "state": "Madhya Pradesh",
    "year": "2018-19",
    "Primary": 3.3,
    "UpperPrimary": 5.9,
    "Secondary": 24.9,
    "Primary_Boys": 2.64,
    "Primary_Girls": 3.96,
    "UpperPrimary_Boys": 4.98,
    "UpperPrimary_Girls": 6.82,
    "Secondary_Boys": 24.97,
    "Secondary_Girls": 24.83
  },
  {
    "state": "Maharashtra",
    "year": "2018-19",
    "Primary": 1.1,
    "UpperPrimary": 2.2,
    "Secondary": 13.3,
    "Primary_Boys": 0,
    "Primary_Girls": 2.2,
    "UpperPrimary_Boys": 1.72,
    "UpperPrimary_Girls": 2.68,
    "Secondary_Boys": 13.56,
    "Secondary_Girls": 13.04
  },
  {
    "state": "Manipur",
    "year": "2018-19",
    "Primary": 6.1,
    "UpperPrimary": 3.4,
    "Secondary": 13.0,
    "Primary_Boys": 5.21,
    "Primary_Girls": 6.99,
    "UpperPrimary_Boys": 1.85,
    "UpperPrimary_Girls": 4.95,
    "Secondary_Boys": 13.3,
    "Secondary_Girls": 12.7
  },
  {
    "state": "Meghalaya",
    "year": "2018-19",
    "Primary": 16.9,
    "UpperPrimary": 9.5,
    "Secondary": 19.5,
    "Primary_Boys": 16.81,
    "Primary_Girls": 16.99,
    "UpperPrimary_Boys": 7.02,
    "UpperPrimary_Girls": 11.98,
    "Secondary_Boys": 18.23,
    "Secondary_Girls": 20.77
  },
  {
    "state": "Mizoram",
    "year": "2018-19",
    "Primary": 7.5,
    "UpperPrimary": 3.1,
    "Secondary": 10.6,
    "Primary_Boys": 6.97,
    "Primary_Girls": 8.03,
    "UpperPrimary_Boys": 2.29,
    "UpperPrimary_Girls": 3.91,
    "Secondary_Boys": 11.18,
    "Secondary_Girls": 10.02
  },
  {
    "state": "Nagaland",
    "year": "2018-19",
    "Primary": 11.4,
    "UpperPrimary": 4.6,
    "Secondary": 24.1,
    "Primary_Boys": 11.61,
    "Primary_Girls": 11.19,
    "UpperPrimary_Boys": 4.42,
    "UpperPrimary_Girls": 4.78,
    "Secondary_Boys": 23.04,
    "Secondary_Girls": 25.16
  },
  {
    "state": "Odisha",
    "year": "2018-19",
    "Primary": 3.4,
    "UpperPrimary": 5.0,
    "Secondary": 9.5,
    "Primary_Boys": 3.59,
    "Primary_Girls": 3.21,
    "UpperPrimary_Boys": 5.23,
    "UpperPrimary_Girls": 4.77,
    "Secondary_Boys": 10.25,
    "Secondary_Girls": 8.75
  },
  {
    "state": "Puducherry",
    "year": "2018-19",
    "Primary": 0.6,
    "UpperPrimary": 0.1,
    "Secondary": 12.7,
    "Primary_Boys": 0,
    "Primary_Girls": 1.2,
    "UpperPrimary_Boys": 0.2,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 10.53,
    "Secondary_Girls": 14.87
  },
  {
    "state": "Punjab",
    "year": "2018-19",
    "Primary": 1.4,
    "UpperPrimary": 2.9,
    "Secondary": 11.5,
    "Primary_Boys": 0,
    "Primary_Girls": 2.8,
    "UpperPrimary_Boys": 3.65,
    "UpperPrimary_Girls": 2.15,
    "Secondary_Boys": 11.67,
    "Secondary_Girls": 11.33
  },
  {
    "state": "Rajasthan",
    "year": "2018-19",
    "Primary": 5.2,
    "UpperPrimary": 3.8,
    "Secondary": 12.7,
    "Primary_Boys": 3.86,
    "Primary_Girls": 6.54,
    "UpperPrimary_Boys": 4.05,
    "UpperPrimary_Girls": 3.55,
    "Secondary_Boys": 13.24,
    "Secondary_Girls": 12.16
  },
  {
    "state": "Sikkim",
    "year": "2018-19",
    "Primary": 5.4,
    "UpperPrimary": 1.1,
    "Secondary": 23.7,
    "Primary_Boys": 3.13,
    "Primary_Girls": 7.67,
    "UpperPrimary_Boys": 0.1,
    "UpperPrimary_Girls": 2.1,
    "Secondary_Boys": 23.05,
    "Secondary_Girls": 24.35
  },
  {
    "state": "Tamil Nadu",
    "year": "2018-19",
    "Primary": 1.2,
    "UpperPrimary": 0.6,
    "Secondary": 13.0,
    "Primary_Boys": 0,
    "Primary_Girls": 2.4,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.2,
    "Secondary_Boys": 13.33,
    "Secondary_Girls": 12.67
  },
  {
    "state": "Telangana",
    "year": "2018-19",
    "Primary": 1.9,
    "UpperPrimary": 2.9,
    "Secondary": 13.5,
    "Primary_Boys": 2.56,
    "Primary_Girls": 1.24,
    "UpperPrimary_Boys": 2.39,
    "UpperPrimary_Girls": 3.41,
    "Secondary_Boys": 13.02,
    "Secondary_Girls": 13.98
  },
  {
    "state": "Tripura",
    "year": "2018-19",
    "Primary": 3.1,
    "UpperPrimary": 4.3,
    "Secondary": 29.6,
    "Primary_Boys": 2.47,
    "Primary_Girls": 3.73,
    "UpperPrimary_Boys": 2.75,
    "UpperPrimary_Girls": 5.85,
    "Secondary_Boys": 28.24,
    "Secondary_Girls": 30.96
  },
  {
    "state": "Uttarakhand",
    "year": "2018-19",
    "Primary": 3.7,
    "UpperPrimary": 3.7,
    "Secondary": 11.0,
    "Primary_Boys": 1.26,
    "Primary_Girls": 6.14,
    "UpperPrimary_Boys": 4.36,
    "UpperPrimary_Girls": 3.04,
    "Secondary_Boys": 10.59,
    "Secondary_Girls": 11.41
  },
  {
    "state": "Uttar Pradesh",
    "year": "2018-19",
    "Primary": 9.7,
    "UpperPrimary": 5.7,
    "Secondary": 15.5,
    "Primary_Boys": 9.51,
    "Primary_Girls": 9.89,
    "UpperPrimary_Boys": 3.68,
    "UpperPrimary_Girls": 7.72,
    "Secondary_Boys": 15.63,
    "Secondary_Girls": 15.37
  },
  {
    "state": "West Bengal",
    "year": "2018-19",
    "Primary": 3.5,
    "UpperPrimary": 1.5,
    "Secondary": 19.5,
    "Primary_Boys": 3.83,
    "Primary_Girls": 3.17,
    "UpperPrimary_Boys": 0.93,
    "UpperPrimary_Girls": 2.07,
    "Secondary_Boys": 19.02,
    "Secondary_Girls": 19.98
  },
  {
    "state": "All India",
    "year": "2018-19",
    "Primary": 4.5,
    "UpperPrimary": 4.7,
    "Secondary": 17.9,
    "Primary_Boys": 4.53,
    "Primary_Girls": 4.47,
    "UpperPrimary_Boys": 4.83,
    "UpperPrimary_Girls": 4.57,
    "Secondary_Boys": 15.67,
    "Secondary_Girls": 20.13
  },
  {
    "state": "Andaman & Nicobar Islands",
    "year": "2019-20",
    "Primary": 0.5,
    "UpperPrimary": 0.0,
    "Secondary": 15.7,
    "Primary_Boys": 0,
    "Primary_Girls": 1.0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 13.69,
    "Secondary_Girls": 17.71
  },
  {
    "state": "Andhra Pradesh",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.3,
    "Secondary": 14.8,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.6,
    "Secondary_Boys": 15.62,
    "Secondary_Girls": 13.98
  },
  {
    "state": "Arunachal Pradesh",
    "year": "2019-20",
    "Primary": 6.2,
    "UpperPrimary": 7.5,
    "Secondary": 34.3,
    "Primary_Boys": 3.7,
    "Primary_Girls": 8.7,
    "UpperPrimary_Boys": 5.57,
    "UpperPrimary_Girls": 9.43,
    "Secondary_Boys": 31.91,
    "Secondary_Girls": 36.69
  },
  {
    "state": "Assam",
    "year": "2019-20",
    "Primary": 4.3,
    "UpperPrimary": 3.4,
    "Secondary": 32.3,
    "Primary_Boys": 2.06,
    "Primary_Girls": 6.54,
    "UpperPrimary_Boys": 1.43,
    "UpperPrimary_Girls": 5.37,
    "Secondary_Boys": 32.72,
    "Secondary_Girls": 31.88
  },
  {
    "state": "Bihar",
    "year": "2019-20",
    "Primary": 2.3,
    "UpperPrimary": 8.9,
    "Secondary": 21.4,
    "Primary_Boys": 1.6,
    "Primary_Girls": 3.0,
    "UpperPrimary_Boys": 9.15,
    "UpperPrimary_Girls": 8.65,
    "Secondary_Boys": 21.0,
    "Secondary_Girls": 21.8
  },
  {
    "state": "Chandigarh",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.3,
    "Secondary": 4.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.6,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 4.37,
    "Secondary_Girls": 5.03
  },
  {
    "state": "Chhattisgarh",
    "year": "2019-20",
    "Primary": 1.0,
    "UpperPrimary": 3.8,
    "Secondary": 18.3,
    "Primary_Boys": 0,
    "Primary_Girls": 2.0,
    "UpperPrimary_Boys": 3.87,
    "UpperPrimary_Girls": 3.73,
    "Secondary_Boys": 16.56,
    "Secondary_Girls": 20.04
  },
  {
    "state": "Dadra & Nagar Haveli",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 20.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.51,
    "UpperPrimary_Girls": 1.69,
    "Secondary_Boys": 19.82,
    "Secondary_Girls": 20.78
  },
  {
    "state": "Daman & Diu",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 20.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 17.65,
    "Secondary_Girls": 22.35
  },
  {
    "state": "Delhi",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.2,
    "Secondary": 13.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.4,
    "Secondary_Boys": 12.95,
    "Secondary_Girls": 14.85
  },
  {
    "state": "Goa",
    "year": "2019-20",
    "Primary": 0.3,
    "UpperPrimary": 0.0,
    "Secondary": 10.2,
    "Primary_Boys": 0,
    "Primary_Girls": 0.6,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 10.66,
    "Secondary_Girls": 9.74
  },
  {
    "state": "Gujarat",
    "year": "2019-20",
    "Primary": 1.0,
    "UpperPrimary": 5.2,
    "Secondary": 23.7,
    "Primary_Boys": 0.96,
    "Primary_Girls": 1.04,
    "UpperPrimary_Boys": 2.81,
    "UpperPrimary_Girls": 7.59,
    "Secondary_Boys": 22.67,
    "Secondary_Girls": 24.73
  },
  {
    "state": "Haryana",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 1.8,
    "Secondary": 13.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.9,
    "UpperPrimary_Girls": 2.7,
    "Secondary_Boys": 11.68,
    "Secondary_Girls": 14.92
  },
  {
    "state": "Himachal Pradesh",
    "year": "2019-20",
    "Primary": 0.9,
    "UpperPrimary": 0.6,
    "Secondary": 7.2,
    "Primary_Boys": 1.7,
    "Primary_Girls": 0.1,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.2,
    "Secondary_Boys": 6.44,
    "Secondary_Girls": 7.96
  },
  {
    "state": "Jammu & Kashmir",
    "year": "2019-20",
    "Primary": 5.9,
    "UpperPrimary": 5.1,
    "Secondary": 18.5,
    "Primary_Boys": 3.92,
    "Primary_Girls": 7.88,
    "UpperPrimary_Boys": 5.55,
    "UpperPrimary_Girls": 4.65,
    "Secondary_Boys": 16.14,
    "Secondary_Girls": 20.86
  },
  {
    "state": "Jharkhand",
    "year": "2019-20",
    "Primary": 6.3,
    "UpperPrimary": 8.5,
    "Secondary": 16.6,
    "Primary_Boys": 7.02,
    "Primary_Girls": 5.58,
    "UpperPrimary_Boys": 8.85,
    "UpperPrimary_Girls": 8.15,
    "Secondary_Boys": 15.52,
    "Secondary_Girls": 17.68
  },
  {
    "state": "Karnataka",
    "year": "2019-20",
    "Primary": 1.2,
    "UpperPrimary": 2.5,
    "Secondary": 16.8,
    "Primary_Boys": 0,
    "Primary_Girls": 2.4,
    "UpperPrimary_Boys": 2.68,
    "UpperPrimary_Girls": 2.32,
    "Secondary_Boys": 17.38,
    "Secondary_Girls": 16.22
  },
  {
    "state": "Kerala",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 7.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 5.78,
    "Secondary_Girls": 10.02
  },
  {
    "state": "Lakshadweep",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 6.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 6.84,
    "Secondary_Girls": 6.56
  },
  {
    "state": "Madhya Pradesh",
    "year": "2019-20",
    "Primary": 0.8,
    "UpperPrimary": 4.1,
    "Secondary": 23.2,
    "Primary_Boys": 0,
    "Primary_Girls": 1.6,
    "UpperPrimary_Boys": 2.93,
    "UpperPrimary_Girls": 5.27,
    "Secondary_Boys": 22.73,
    "Secondary_Girls": 23.67
  },
  {
    "state": "Maharashtra",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 15.2,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.06,
    "UpperPrimary_Girls": 2.14,
    "Secondary_Boys": 14.37,
    "Secondary_Girls": 16.03
  },
  {
    "state": "Manipur",
    "year": "2019-20",
    "Primary": 8.8,
    "UpperPrimary": 4.0,
    "Secondary": 9.2,
    "Primary_Boys": 6.53,
    "Primary_Girls": 11.07,
    "UpperPrimary_Boys": 4.29,
    "UpperPrimary_Girls": 3.71,
    "Secondary_Boys": 7.69,
    "Secondary_Girls": 10.71
  },
  {
    "state": "Meghalaya",
    "year": "2019-20",
    "Primary": 7.0,
    "UpperPrimary": 8.0,
    "Secondary": 22.2,
    "Primary_Boys": 7.16,
    "Primary_Girls": 6.84,
    "UpperPrimary_Boys": 7.61,
    "UpperPrimary_Girls": 8.39,
    "Secondary_Boys": 20.85,
    "Secondary_Girls": 23.55
  },
  {
    "state": "Mizoram",
    "year": "2019-20",
    "Primary": 7.8,
    "UpperPrimary": 2.5,
    "Secondary": 20.4,
    "Primary_Boys": 7.75,
    "Primary_Girls": 7.85,
    "UpperPrimary_Boys": 2.39,
    "UpperPrimary_Girls": 2.61,
    "Secondary_Boys": 18.77,
    "Secondary_Girls": 22.03
  },
  {
    "state": "Nagaland",
    "year": "2019-20",
    "Primary": 4.2,
    "UpperPrimary": 5.4,
    "Secondary": 21.2,
    "Primary_Boys": 4.95,
    "Primary_Girls": 3.45,
    "UpperPrimary_Boys": 4.8,
    "UpperPrimary_Girls": 6.0,
    "Secondary_Boys": 18.71,
    "Secondary_Girls": 23.69
  },
  {
    "state": "Odisha",
    "year": "2019-20",
    "Primary": 0.8,
    "UpperPrimary": 4.5,
    "Secondary": 23.6,
    "Primary_Boys": 0,
    "Primary_Girls": 1.6,
    "UpperPrimary_Boys": 5.24,
    "UpperPrimary_Girls": 3.76,
    "Secondary_Boys": 23.85,
    "Secondary_Girls": 23.35
  },
  {
    "state": "Puducherry",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 7.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 7.97,
    "Secondary_Girls": 7.83
  },
  {
    "state": "Punjab",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 1.6,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 0,
    "Secondary_Girls": 3.2
  },
  {
    "state": "Rajasthan",
    "year": "2019-20",
    "Primary": 2.9,
    "UpperPrimary": 1.5,
    "Secondary": 12.3,
    "Primary_Boys": 0.82,
    "Primary_Girls": 4.98,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 3.0,
    "Secondary_Boys": 12.01,
    "Secondary_Girls": 12.59
  },
  {
    "state": "Sikkim",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 23.2,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 23.65,
    "Secondary_Girls": 22.75
  },
  {
    "state": "Tamil Nadu",
    "year": "2019-20",
    "Primary": 1.1,
    "UpperPrimary": 0.4,
    "Secondary": 9.6,
    "Primary_Boys": 0,
    "Primary_Girls": 2.2,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 8.46,
    "Secondary_Girls": 10.74
  },
  {
    "state": "Telangana",
    "year": "2019-20",
    "Primary": 0.0,
    "UpperPrimary": 0.1,
    "Secondary": 12.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.2,
    "Secondary_Boys": 11.01,
    "Secondary_Girls": 13.59
  },
  {
    "state": "Tripura",
    "year": "2019-20",
    "Primary": 2.0,
    "UpperPrimary": 3.5,
    "Secondary": 26.7,
    "Primary_Boys": 2.97,
    "Primary_Girls": 1.03,
    "UpperPrimary_Boys": 1.64,
    "UpperPrimary_Girls": 5.36,
    "Secondary_Boys": 26.65,
    "Secondary_Girls": 26.75
  },
  {
    "state": "Uttarakhand",
    "year": "2019-20",
    "Primary": 2.5,
    "UpperPrimary": 2.3,
    "Secondary": 8.4,
    "Primary_Boys": 1.18,
    "Primary_Girls": 3.82,
    "UpperPrimary_Boys": 0.01,
    "UpperPrimary_Girls": 4.59,
    "Secondary_Boys": 8.93,
    "Secondary_Girls": 7.87
  },
  {
    "state": "Uttar Pradesh",
    "year": "2019-20",
    "Primary": 2.7,
    "UpperPrimary": 2.1,
    "Secondary": 14.4,
    "Primary_Boys": 3.3,
    "Primary_Girls": 2.1,
    "UpperPrimary_Boys": 2.73,
    "UpperPrimary_Girls": 1.47,
    "Secondary_Boys": 13.46,
    "Secondary_Girls": 15.34
  },
  {
    "state": "West Bengal",
    "year": "2019-20",
    "Primary": 0.6,
    "UpperPrimary": 0.0,
    "Secondary": 13.8,
    "Primary_Boys": 0.65,
    "Primary_Girls": 0.55,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 12.68,
    "Secondary_Girls": 14.92
  },
  {
    "state": "All India",
    "year": "2019-20",
    "Primary": 1.5,
    "UpperPrimary": 2.6,
    "Secondary": 16.1,
    "Primary_Boys": 0,
    "Primary_Girls": 3.0,
    "UpperPrimary_Boys": 2.89,
    "UpperPrimary_Girls": 2.31,
    "Secondary_Boys": 14.88,
    "Secondary_Girls": 17.32
  },
  {
    "state": "Andaman & Nicobar Islands",
    "year": "2020-21",
    "Primary": 2.3,
    "UpperPrimary": 0.4,
    "Secondary": 7.0,
    "Primary_Boys": 2.38,
    "Primary_Girls": 2.22,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 4.83,
    "Secondary_Girls": 9.17
  },
  {
    "state": "Andhra Pradesh",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.5,
    "Secondary": 16.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.0,
    "Secondary_Boys": 17.38,
    "Secondary_Girls": 16.02
  },
  {
    "state": "Arunachal Pradesh",
    "year": "2020-21",
    "Primary": 8.1,
    "UpperPrimary": 7.1,
    "Secondary": 10.1,
    "Primary_Boys": 7.62,
    "Primary_Girls": 8.58,
    "UpperPrimary_Boys": 7.13,
    "UpperPrimary_Girls": 7.07,
    "Secondary_Boys": 11.09,
    "Secondary_Girls": 9.11
  },
  {
    "state": "Assam",
    "year": "2020-21",
    "Primary": 3.3,
    "UpperPrimary": 4.9,
    "Secondary": 30.3,
    "Primary_Boys": 1.6,
    "Primary_Girls": 5.0,
    "UpperPrimary_Boys": 3.67,
    "UpperPrimary_Girls": 6.13,
    "Secondary_Boys": 30.38,
    "Secondary_Girls": 30.22
  },
  {
    "state": "Bihar",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 2.8,
    "Secondary": 17.6,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.21,
    "UpperPrimary_Girls": 4.39,
    "Secondary_Boys": 16.67,
    "Secondary_Girls": 18.53
  },
  {
    "state": "Chandigarh",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.4,
    "Secondary": 0.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.8,
    "Secondary_Boys": 0,
    "Secondary_Girls": 0
  },
  {
    "state": "Chhattisgarh",
    "year": "2020-21",
    "Primary": 0.7,
    "UpperPrimary": 4.1,
    "Secondary": 13.4,
    "Primary_Boys": 1.4,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 4.84,
    "UpperPrimary_Girls": 3.36,
    "Secondary_Boys": 11.31,
    "Secondary_Girls": 15.49
  },
  {
    "state": "Dadra & Nagar Haveli",
    "year": "2020-21",
    "Primary": 2.6,
    "UpperPrimary": 0.6,
    "Secondary": 18.8,
    "Primary_Boys": 0.44,
    "Primary_Girls": 4.76,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.2,
    "Secondary_Boys": 16.88,
    "Secondary_Girls": 20.72
  },
  {
    "state": "Daman & Diu",
    "year": "2020-21",
    "Primary": 6.9,
    "UpperPrimary": 3.6,
    "Secondary": 15.4,
    "Primary_Boys": 5.86,
    "Primary_Girls": 7.94,
    "UpperPrimary_Boys": 4.08,
    "UpperPrimary_Girls": 3.12,
    "Secondary_Boys": 15.95,
    "Secondary_Girls": 14.85
  },
  {
    "state": "Delhi",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 6.1,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 1.02,
    "UpperPrimary_Girls": 1.18,
    "Secondary_Boys": 3.95,
    "Secondary_Girls": 8.25
  },
  {
    "state": "Goa",
    "year": "2020-21",
    "Primary": 1.5,
    "UpperPrimary": 0.8,
    "Secondary": 5.7,
    "Primary_Boys": 0,
    "Primary_Girls": 3.0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.6,
    "Secondary_Boys": 3.55,
    "Secondary_Girls": 7.85
  },
  {
    "state": "Gujarat",
    "year": "2020-21",
    "Primary": 1.0,
    "UpperPrimary": 4.5,
    "Secondary": 23.3,
    "Primary_Boys": 1.26,
    "Primary_Girls": 0.74,
    "UpperPrimary_Boys": 4.63,
    "UpperPrimary_Girls": 4.37,
    "Secondary_Boys": 23.94,
    "Secondary_Girls": 22.66
  },
  {
    "state": "Haryana",
    "year": "2020-21",
    "Primary": 2.1,
    "UpperPrimary": 1.8,
    "Secondary": 10.8,
    "Primary_Boys": 0.37,
    "Primary_Girls": 3.83,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 3.6,
    "Secondary_Boys": 10.38,
    "Secondary_Girls": 11.22
  },
  {
    "state": "Himachal Pradesh",
    "year": "2020-21",
    "Primary": 1.9,
    "UpperPrimary": 1.4,
    "Secondary": 7.6,
    "Primary_Boys": 0.73,
    "Primary_Girls": 3.07,
    "UpperPrimary_Boys": 1.86,
    "UpperPrimary_Girls": 0.94,
    "Secondary_Boys": 5.35,
    "Secondary_Girls": 9.85
  },
  {
    "state": "Jammu & Kashmir",
    "year": "2020-21",
    "Primary": 4.4,
    "UpperPrimary": 3.4,
    "Secondary": 3.7,
    "Primary_Boys": 2.37,
    "Primary_Girls": 6.43,
    "UpperPrimary_Boys": 0.98,
    "UpperPrimary_Girls": 5.82,
    "Secondary_Boys": 1.86,
    "Secondary_Girls": 5.54
  },
  {
    "state": "Jharkhand",
    "year": "2020-21",
    "Primary": 3.5,
    "UpperPrimary": 5.4,
    "Secondary": 13.0,
    "Primary_Boys": 1.42,
    "Primary_Girls": 5.58,
    "UpperPrimary_Boys": 6.31,
    "UpperPrimary_Girls": 4.49,
    "Secondary_Boys": 11.42,
    "Secondary_Girls": 14.58
  },
  {
    "state": "Karnataka",
    "year": "2020-21",
    "Primary": 1.1,
    "UpperPrimary": 2.0,
    "Secondary": 16.6,
    "Primary_Boys": 0.94,
    "Primary_Girls": 1.26,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 4.0,
    "Secondary_Boys": 14.79,
    "Secondary_Girls": 18.41
  },
  {
    "state": "Kerala",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 7.1,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 5.08,
    "Secondary_Girls": 9.12
  },
  {
    "state": "Ladakh",
    "year": "2020-21",
    "Primary": 4.1,
    "UpperPrimary": 2.1,
    "Secondary": 3.4,
    "Primary_Boys": 2.26,
    "Primary_Girls": 5.94,
    "UpperPrimary_Boys": 2.17,
    "UpperPrimary_Girls": 2.03,
    "Secondary_Boys": 1.64,
    "Secondary_Girls": 5.16
  },
  {
    "state": "Lakshadweep",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 0.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 0,
    "Secondary_Girls": 0
  },
  {
    "state": "Madhya Pradesh",
    "year": "2020-21",
    "Primary": 1.3,
    "UpperPrimary": 6.4,
    "Secondary": 23.8,
    "Primary_Boys": 1.92,
    "Primary_Girls": 0.68,
    "UpperPrimary_Boys": 4.35,
    "UpperPrimary_Girls": 8.45,
    "Secondary_Boys": 21.79,
    "Secondary_Girls": 25.81
  },
  {
    "state": "Maharashtra",
    "year": "2020-21",
    "Primary": 1.0,
    "UpperPrimary": 1.5,
    "Secondary": 11.2,
    "Primary_Boys": 1.22,
    "Primary_Girls": 0.78,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 3.0,
    "Secondary_Boys": 10.59,
    "Secondary_Girls": 11.81
  },
  {
    "state": "Manipur",
    "year": "2020-21",
    "Primary": 8.5,
    "UpperPrimary": 4.0,
    "Secondary": 9.4,
    "Primary_Boys": 8.43,
    "Primary_Girls": 8.57,
    "UpperPrimary_Boys": 2.22,
    "UpperPrimary_Girls": 5.78,
    "Secondary_Boys": 9.6,
    "Secondary_Girls": 9.2
  },
  {
    "state": "Meghalaya",
    "year": "2020-21",
    "Primary": 7.4,
    "UpperPrimary": 9.0,
    "Secondary": 27.6,
    "Primary_Boys": 8.32,
    "Primary_Girls": 6.48,
    "UpperPrimary_Boys": 9.32,
    "UpperPrimary_Girls": 8.68,
    "Secondary_Boys": 27.45,
    "Secondary_Girls": 27.75
  },
  {
    "state": "Mizoram",
    "year": "2020-21",
    "Primary": 8.1,
    "UpperPrimary": 5.3,
    "Secondary": 20.0,
    "Primary_Boys": 6.07,
    "Primary_Girls": 10.13,
    "UpperPrimary_Boys": 2.92,
    "UpperPrimary_Girls": 7.68,
    "Secondary_Boys": 20.02,
    "Secondary_Girls": 19.98
  },
  {
    "state": "Nagaland",
    "year": "2020-21",
    "Primary": 5.9,
    "UpperPrimary": 4.2,
    "Secondary": 23.6,
    "Primary_Boys": 4.65,
    "Primary_Girls": 7.15,
    "UpperPrimary_Boys": 3.8,
    "UpperPrimary_Girls": 4.6,
    "Secondary_Boys": 21.17,
    "Secondary_Girls": 26.03
  },
  {
    "state": "Odisha",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 16.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 15.12,
    "Secondary_Girls": 16.88
  },
  {
    "state": "Puducherry",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 6.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 4.61,
    "Secondary_Girls": 9.19
  },
  {
    "state": "Punjab",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 9.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 9.6,
    "Secondary_Girls": 8.4
  },
  {
    "state": "Rajasthan",
    "year": "2020-21",
    "Primary": 1.0,
    "UpperPrimary": 2.7,
    "Secondary": 8.9,
    "Primary_Boys": 0,
    "Primary_Girls": 2.0,
    "UpperPrimary_Boys": 3.08,
    "UpperPrimary_Girls": 2.32,
    "Secondary_Boys": 6.53,
    "Secondary_Girls": 11.27
  },
  {
    "state": "Sikkim",
    "year": "2020-21",
    "Primary": 1.2,
    "UpperPrimary": 0.0,
    "Secondary": 21.6,
    "Primary_Boys": 1.27,
    "Primary_Girls": 1.13,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 22.22,
    "Secondary_Girls": 20.98
  },
  {
    "state": "Tamil Nadu",
    "year": "2020-21",
    "Primary": 0.6,
    "UpperPrimary": 0.6,
    "Secondary": 6.4,
    "Primary_Boys": 0.08,
    "Primary_Girls": 1.12,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 1.2,
    "Secondary_Boys": 6.3,
    "Secondary_Girls": 6.5
  },
  {
    "state": "Telangana",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 13.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 12.78,
    "Secondary_Girls": 15.02
  },
  {
    "state": "Tripura",
    "year": "2020-21",
    "Primary": 4.2,
    "UpperPrimary": 5.5,
    "Secondary": 26.7,
    "Primary_Boys": 3.41,
    "Primary_Girls": 4.99,
    "UpperPrimary_Boys": 5.15,
    "UpperPrimary_Girls": 5.85,
    "Secondary_Boys": 25.68,
    "Secondary_Girls": 27.72
  },
  {
    "state": "Uttarakhand",
    "year": "2020-21",
    "Primary": 1.7,
    "UpperPrimary": 2.1,
    "Secondary": 8.3,
    "Primary_Boys": 1.81,
    "Primary_Girls": 1.59,
    "UpperPrimary_Boys": 0.62,
    "UpperPrimary_Girls": 3.58,
    "Secondary_Boys": 9.29,
    "Secondary_Girls": 7.31
  },
  {
    "state": "Uttar Pradesh",
    "year": "2020-21",
    "Primary": 2.2,
    "UpperPrimary": 4.6,
    "Secondary": 12.5,
    "Primary_Boys": 0,
    "Primary_Girls": 4.4,
    "UpperPrimary_Boys": 3.72,
    "UpperPrimary_Girls": 5.48,
    "Secondary_Boys": 10.98,
    "Secondary_Girls": 14.02
  },
  {
    "state": "West Bengal",
    "year": "2020-21",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 13.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 11.7,
    "Secondary_Girls": 14.9
  },
  {
    "state": "All India",
    "year": "2020-21",
    "Primary": 0.8,
    "UpperPrimary": 2.3,
    "Secondary": 14.0,
    "Primary_Boys": 0,
    "Primary_Girls": 1.6,
    "UpperPrimary_Boys": 2.03,
    "UpperPrimary_Girls": 2.57,
    "Secondary_Boys": 14.76,
    "Secondary_Girls": 13.24
  },
  {
    "state": "Andaman & Nicobar Islands",
    "year": "2021-22",
    "Primary": 0.4,
    "UpperPrimary": 1.0,
    "Secondary": 5.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0.8,
    "UpperPrimary_Boys": 0.84,
    "UpperPrimary_Girls": 1.16,
    "Secondary_Boys": 4.9,
    "Secondary_Girls": 5.1
  },
  {
    "state": "Andhra Pradesh",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 1.6,
    "Secondary": 16.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 3.2,
    "Secondary_Boys": 14.78,
    "Secondary_Girls": 17.82
  },
  {
    "state": "Arunachal Pradesh",
    "year": "2021-22",
    "Primary": 9.3,
    "UpperPrimary": 6.7,
    "Secondary": 11.7,
    "Primary_Boys": 9.25,
    "Primary_Girls": 9.35,
    "UpperPrimary_Boys": 6.62,
    "UpperPrimary_Girls": 6.78,
    "Secondary_Boys": 11.27,
    "Secondary_Girls": 12.13
  },
  {
    "state": "Assam",
    "year": "2021-22",
    "Primary": 6.0,
    "UpperPrimary": 8.8,
    "Secondary": 20.3,
    "Primary_Boys": 5.59,
    "Primary_Girls": 6.41,
    "UpperPrimary_Boys": 8.77,
    "UpperPrimary_Girls": 8.83,
    "Secondary_Boys": 20.85,
    "Secondary_Girls": 19.75
  },
  {
    "state": "Bihar",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 4.6,
    "Secondary": 20.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 4.13,
    "UpperPrimary_Girls": 5.07,
    "Secondary_Boys": 18.21,
    "Secondary_Girls": 22.79
  },
  {
    "state": "Chandigarh",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 0.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 0,
    "Secondary_Girls": 0
  },
  {
    "state": "Chhattisgarh",
    "year": "2021-22",
    "Primary": 0.8,
    "UpperPrimary": 4.1,
    "Secondary": 9.7,
    "Primary_Boys": 0,
    "Primary_Girls": 1.6,
    "UpperPrimary_Boys": 1.94,
    "UpperPrimary_Girls": 6.26,
    "Secondary_Boys": 8.55,
    "Secondary_Girls": 10.85
  },
  {
    "state": "Dadra & Nagar Haveli",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 9.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 9.45,
    "Secondary_Girls": 9.55
  },
  {
    "state": "Daman & Diu",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 9.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 8.58,
    "Secondary_Girls": 10.42
  },
  {
    "state": "Delhi",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 4.8,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 5.8,
    "Secondary_Girls": 3.8
  },
  {
    "state": "Goa",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 9.0,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 9.0,
    "Secondary_Girls": 9.0
  },
  {
    "state": "Gujarat",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 5.0,
    "Secondary": 17.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 4.5,
    "UpperPrimary_Girls": 5.5,
    "Secondary_Boys": 16.87,
    "Secondary_Girls": 18.93
  },
  {
    "state": "Haryana",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.2,
    "Secondary": 5.9,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0.4,
    "Secondary_Boys": 5.27,
    "Secondary_Girls": 6.53
  },
  {
    "state": "Himachal Pradesh",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.6,
    "Secondary": 1.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0.05,
    "UpperPrimary_Girls": 1.15,
    "Secondary_Boys": 1.75,
    "Secondary_Girls": 1.25
  },
  {
    "state": "Jammu & Kashmir",
    "year": "2021-22",
    "Primary": 4.0,
    "UpperPrimary": 3.0,
    "Secondary": 6.0,
    "Primary_Boys": 3.34,
    "Primary_Girls": 4.66,
    "UpperPrimary_Boys": 0.85,
    "UpperPrimary_Girls": 5.15,
    "Secondary_Boys": 4.21,
    "Secondary_Girls": 7.79
  },
  {
    "state": "Jharkhand",
    "year": "2021-22",
    "Primary": 1.8,
    "UpperPrimary": 3.9,
    "Secondary": 9.3,
    "Primary_Boys": 2.21,
    "Primary_Girls": 1.39,
    "UpperPrimary_Boys": 4.6,
    "UpperPrimary_Girls": 3.2,
    "Secondary_Boys": 8.5,
    "Secondary_Girls": 10.1
  },
  {
    "state": "Karnataka",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 1.1,
    "Secondary": 14.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 2.2,
    "Secondary_Boys": 14.53,
    "Secondary_Girls": 14.87
  },
  {
    "state": "Kerala",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 5.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 3.64,
    "Secondary_Girls": 7.36
  },
  {
    "state": "Ladakh",
    "year": "2021-22",
    "Primary": 6.5,
    "UpperPrimary": 1.1,
    "Secondary": 4.9,
    "Primary_Boys": 4.87,
    "Primary_Girls": 8.13,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 2.2,
    "Secondary_Boys": 5.11,
    "Secondary_Girls": 4.69
  },
  {
    "state": "Lakshadweep",
    "year": "2021-22",
    "Primary": 0.5,
    "UpperPrimary": 2.6,
    "Secondary": 0.0,
    "Primary_Boys": 0.8,
    "Primary_Girls": 0.2,
    "UpperPrimary_Boys": 3.51,
    "UpperPrimary_Girls": 1.69,
    "Secondary_Boys": 0,
    "Secondary_Girls": 0
  },
  {
    "state": "Madhya Pradesh",
    "year": "2021-22",
    "Primary": 3.1,
    "UpperPrimary": 8.8,
    "Secondary": 10.1,
    "Primary_Boys": 3.24,
    "Primary_Girls": 2.96,
    "UpperPrimary_Boys": 8.14,
    "UpperPrimary_Girls": 9.46,
    "Secondary_Boys": 8.13,
    "Secondary_Girls": 12.07
  },
  {
    "state": "Maharashtra",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 1.5,
    "Secondary": 10.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 2.25,
    "UpperPrimary_Girls": 0.75,
    "Secondary_Boys": 10.25,
    "Secondary_Girls": 11.15
  },
  {
    "state": "Manipur",
    "year": "2021-22",
    "Primary": 13.3,
    "UpperPrimary": 5.6,
    "Secondary": 1.3,
    "Primary_Boys": 12.1,
    "Primary_Girls": 14.5,
    "UpperPrimary_Boys": 5.92,
    "UpperPrimary_Girls": 5.28,
    "Secondary_Boys": 0,
    "Secondary_Girls": 2.6
  },
  {
    "state": "Meghalaya",
    "year": "2021-22",
    "Primary": 9.8,
    "UpperPrimary": 10.6,
    "Secondary": 21.7,
    "Primary_Boys": 9.07,
    "Primary_Girls": 10.53,
    "UpperPrimary_Boys": 10.75,
    "UpperPrimary_Girls": 10.45,
    "Secondary_Boys": 20.4,
    "Secondary_Girls": 23.0
  },
  {
    "state": "Mizoram",
    "year": "2021-22",
    "Primary": 6.4,
    "UpperPrimary": 2.7,
    "Secondary": 11.9,
    "Primary_Boys": 7.38,
    "Primary_Girls": 5.42,
    "UpperPrimary_Boys": 1.07,
    "UpperPrimary_Girls": 4.33,
    "Secondary_Boys": 10.2,
    "Secondary_Girls": 13.6
  },
  {
    "state": "Nagaland",
    "year": "2021-22",
    "Primary": 5.0,
    "UpperPrimary": 4.0,
    "Secondary": 17.5,
    "Primary_Boys": 5.63,
    "Primary_Girls": 4.37,
    "UpperPrimary_Boys": 3.51,
    "UpperPrimary_Girls": 4.49,
    "Secondary_Boys": 17.88,
    "Secondary_Girls": 17.12
  },
  {
    "state": "Odisha",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 7.3,
    "Secondary": 27.3,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 4.95,
    "UpperPrimary_Girls": 9.65,
    "Secondary_Boys": 26.49,
    "Secondary_Girls": 28.11
  },
  {
    "state": "Puducherry",
    "year": "2021-22",
    "Primary": 3.7,
    "UpperPrimary": 2.4,
    "Secondary": 6.3,
    "Primary_Boys": 4.52,
    "Primary_Girls": 2.88,
    "UpperPrimary_Boys": 2.53,
    "UpperPrimary_Girls": 2.27,
    "Secondary_Boys": 4.33,
    "Secondary_Girls": 8.27
  },
  {
    "state": "Punjab",
    "year": "2021-22",
    "Primary": 1.3,
    "UpperPrimary": 8.0,
    "Secondary": 17.2,
    "Primary_Boys": 0.7,
    "Primary_Girls": 1.9,
    "UpperPrimary_Boys": 6.2,
    "UpperPrimary_Girls": 9.8,
    "Secondary_Boys": 15.86,
    "Secondary_Girls": 18.54
  },
  {
    "state": "Rajasthan",
    "year": "2021-22",
    "Primary": 3.6,
    "UpperPrimary": 4.3,
    "Secondary": 7.7,
    "Primary_Boys": 1.14,
    "Primary_Girls": 6.06,
    "UpperPrimary_Boys": 3.22,
    "UpperPrimary_Girls": 5.38,
    "Secondary_Boys": 5.37,
    "Secondary_Girls": 10.03
  },
  {
    "state": "Sikkim",
    "year": "2021-22",
    "Primary": 1.8,
    "UpperPrimary": 0.0,
    "Secondary": 11.9,
    "Primary_Boys": 0,
    "Primary_Girls": 3.6,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 10.76,
    "Secondary_Girls": 13.04
  },
  {
    "state": "Tamil Nadu",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 0.0,
    "Secondary": 4.5,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 2.98,
    "Secondary_Girls": 6.02
  },
  {
    "state": "Telangana",
    "year": "2021-22",
    "Primary": 0.0,
    "UpperPrimary": 3.1,
    "Secondary": 13.7,
    "Primary_Boys": 0,
    "Primary_Girls": 0,
    "UpperPrimary_Boys": 2.33,
    "UpperPrimary_Girls": 3.87,
    "Secondary_Boys": 11.79,
    "Secondary_Girls": 15.61
  },
  {
    "state": "Tripura",
    "year": "2021-22",
    "Primary": 1.1,
    "UpperPrimary": 4.5,
    "Secondary": 8.3,
    "Primary_Boys": 0.18,
    "Primary_Girls": 2.02,
    "UpperPrimary_Boys": 2.36,
    "UpperPrimary_Girls": 6.64,
    "Secondary_Boys": 6.7,
    "Secondary_Girls": 9.9
  },
  {
    "state": "Uttarakhand",
    "year": "2021-22",
    "Primary": 0.8,
    "UpperPrimary": 2.7,
    "Secondary": 5.0,
    "Primary_Boys": 0.14,
    "Primary_Girls": 1.46,
    "UpperPrimary_Boys": 2.79,
    "UpperPrimary_Girls": 2.61,
    "Secondary_Boys": 5.13,
    "Secondary_Girls": 4.87
  },
  {
    "state": "Uttar Pradesh",
    "year": "2021-22",
    "Primary": 2.7,
    "UpperPrimary": 2.9,
    "Secondary": 9.7,
    "Primary_Boys": 1.47,
    "Primary_Girls": 3.93,
    "UpperPrimary_Boys": 1.22,
    "UpperPrimary_Girls": 4.58,
    "Secondary_Boys": 8.88,
    "Secondary_Girls": 10.52
  },
  {
    "state": "West Bengal",
    "year": "2021-22",
    "Primary": 8.6,
    "UpperPrimary": 0.0,
    "Secondary": 18.0,
    "Primary_Boys": 7.41,
    "Primary_Girls": 9.79,
    "UpperPrimary_Boys": 0,
    "UpperPrimary_Girls": 0,
    "Secondary_Boys": 18.04,
    "Secondary_Girls": 17.96
  },
  {
    "state": "All India",
    "year": "2021-22",
    "Primary": 1.5,
    "UpperPrimary": 3.0,
    "Secondary": 12.6,
    "Primary_Boys": 2.23,
    "Primary_Girls": 0.77,
    "UpperPrimary_Boys": 3.0,
    "UpperPrimary_Girls": 3.0,
    "Secondary_Boys": 12.65,
    "Secondary_Girls": 12.55
  }
];

export const newYears = ["2017-18", "2018-19", "2019-20", "2020-21", "2021-22"];

export const getNewDataByYear = (year) => {
  return newDorData.filter(d => d.year === year && d.state !== "All India");
};

export const getNewNationalAverage = (year) => {
  return newDorData.find(d => d.state === "All India" && d.year === year);
};

export const getNewStates = () => {
  return [...new Set(newDorData.filter(d => d.state !== "All India").map(d => d.state))].sort();
};
